### ISSUE TITLE
Change vault when/if it's added. (vault suggestions thread)

### ISSUE THREAD

**Issue by brobra3333** [BadDeathclaw/TG-Claw#1006]
Basically a list of suggestions for vault so it's not the nothing faction it was before.

1.  Add virology to vault
- Disease and plague should be a part of wasteland life
-Add extreme role play restrictions as to how deadly and when they can release a disease on the wasteland for testing purposes.
--this can be primarily enforced by the overseer.
2. give genetics to vault by default.
-Possibly fits the theme of vault being a bio engineering facility.

**Comment by Dioclex** [comment]
The Vault, as it was, was a waste of potential as it became a drain of players in the wasteland and isolated them for most of the game. The Vault, as shown canonically in lore, does not necessarily have to be an insular and completely cut-off faction, there are ways to work with it. Vault 13 and 81, for example, were forced to open their doors due to a lack of necessary resource. If we allowed the Vault to open up due to a lack of a particular resource, say for example food or uranium, requiring the Vault to either venture out to acquire such necessary resources or instigate trade between savvy merchants and the Vault. In any case, having the Vault being able to interact with the outside world would in effect make it like a more insular Kebab-Town than anything, open up far more opportunities for the Vault Dwellers themselves and sponsor new and intriguing RP situations accordingly. The Vault, as it stands, is in need of change in order to help contribute to the rest of the round, however, to simply remove the issue instead of fixing it would be a massive waste of opportunity and creativity. As such, I think working with an open/semi-open Vault would be the best course of action.

**Comment by brobra3333** [comment]
Yes, I think a semi-open vault would be the best course of action with the overseer having the final say on interaction with the wasteland. The incentive for the vault to remain isolated would be to maintain security over dangerous technology such as virology while it is encourage to open up to the wasteland due to it running low on resources.

**Comment by Commandersand** [comment]
Vault could start as being barely opened up from the inside because of an emergency and people can chose whether or not to go out
example: revolution starts and all of command has their head's on pikes when the round start.
Maybe there should be a crisis in the wasteland that happens at shuttle call that forces people to go in shelter and the vault's the best place

**Comment by walrathdam** [comment]
Something to keep in mind is that an open vault will introduce high level tech to the wasteland more so than the BOS who has an incentive to stay hidden and not share. Their resources should be very limited to prevent them from being stronger than other factions, as well as forcing them to interact with the town and wastes.

**Comment by Hekzder** [comment]
Vault is mostly planned out in terms of what we want to do in regards to changing it. Talk to myself or ma44 for details.
