### ISSUE TITLE
Kebab town's mine is basically useless unless you're using it to hide.

### ISSUE THREAD

**Issue by Bonomedia** [BadDeathclaw/TG-Claw#1127]
We need to add a ORM or something similar somewhere in Kebab Town so they can smelt the ores they get from the mine. They can use it so they can refill their metal and use the other resources to build instead of wasting multiple welding tools to smelt it slowly.

**Comment by Kabramen** [comment]
We already have an alternative to ORM, and is the bonfires (yes you can throw ores on bonfires to melt it). the downside is that you can't mix ores with it, and it doesn't give you 1:1 for ore (it's random).
It was already suggested an rudimentary furnace to be used in place of ORM/bonfire, but I don't think anyone is working on it.

**Comment by FantasticFwoosh** [comment]
Since fuel tanks have been made more reliable, you can still process rare metals 1:1 by welding them &  iron ore + glass can be input directly into the construction lathe, its still far from perfect but functional. Kebab doesn't have a high nessecity for ores without RnD or advanced crafting recipies (arguably making drinks and grinding into reagents + decoration still applies)

The design of the mine and mining the map is a seperate issue, throwing a orm board guarded by a ghoul pit or worthy adversary is one thing, but cave turfs aboveground at-least are a unusable eye sore, coupled with a lack of anything solid to cling on to for plains of brown rock + very spaced apart ores make mining not the most immersive thing to do.
