### ISSUE TITLE
Leather jacket and overcoat missing from crafting

### ISSUE THREAD

**Issue by uzername** [BadDeathclaw/TG-Claw#1132]
[Priority]: # (Is it game breaking?) It made me a little sad

[PR]: # (If you think you know the specific code / PR causing the problem then please do tell.)
This commit: https://github.com/BadDeathclaw/TG-Claw/commit/d1b30676aac4dcf78c4bec05465f5a736e3e28d0  ( Merge pull request #1126 from FantasticFwoosh/civ-tailoring ) removed leather jacket and leather overcoat from crafting list. They are neither on Crafting UI window, nor in a window from direct usage of leather. 

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.) There are two old recipes - get 7 leather and make jacket, or get 10 leather and make long black stylish overcoat. After farming 10 leather pieces expected to be able to craft leather overcoat. Or a jacket. Clicked on leather, and there were not such entries in a window. Opened Crafting menu - and same, no such entries under Clothing category.

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.) I have contacted over ahelp.

[Notes]: # (Other notes.) Please, return them back. I liked these two items

**Comment by FantasticFwoosh** [comment]
Im sorry to hear that, i removed it by deliberate decision because intrinsically it kind of sucked for multiple reasons.

1) It was expensive for a cosmetic item individually, but of F13 you kind of expect good clothes with things like pockets that i did to upscale the poncho, and the jacket & overcoat was untouched straight from the space-station objects with no additional code preparation as is when i wanted more fallout centric clothes from existing fully coded assets.

2) Actual MFP (main force patrol) jacket is better and already fleshed out but obviously a existing world item with lore attached rather than something you make, but i didn't really find a good medium to meet midway with it or manage to differentiate it so I couldnt find a way to do it justice, overcoat neither.

Ill keep it in mind if i approach doing clothes again, in the meantime though just a reminder that the objects still exist fully intact in the files. I've just removed them from leather crafting so there's not much reason why you couldn't make some simple edits if you had creative vision how to implement them back in they way you wanted to and how you'd think would be useful to the community.

**Comment by uzername** [comment]
Why not keep these items as they are in Space Station 13 code? I remember that they do lack pockets and they do not have pretty high armor protection, so they are not balance breaking.

They are just valuable in-game fluff items. Whenever I see someone having leather jacket or overcoat, I am pretty sure, that this must be a successful farmer who wants to stand out with a style.

**Comment by uzername** [comment]
Thanks for merging my PR! Cannot wait to see it in game/
