### ISSUE TITLE
Two Decanus Roles

### ISSUE THREAD

**Issue by companoo** [BadDeathclaw/TG-Claw#179]
Basically, a Centurion should have a clear 2IC, Decanus sort of fills that role but the fact there are three of them undermines it. I propose that similar to Legionary and Veteran Legionary in-game, a Veteran Decanus role is created, with it as the deputy to the Centurion, they can be distinguished by veteran armor? + maybe a new vet Decanus headpiece, which could be sprited with relative ease by recolouring some feathers in the current sprite. This would enhance the legion chain ofcommand, making it relatively like the NCR's, ie, 2sergeants-lieutenant-captain, and on legion side 2recruitdecanus>1vetdecanus>cent

**Comment by RenGusta** [comment]
Just to make this abundantly clear, Vexillarius isn't a 2IC, they're a Flag Bearer and source of Morale.

**Comment by Operativ** [comment]
I agree with you there, in both Legion's lore fluff and in the Roman Empire they were flag-bearers. I just meant that the game points out that the Vexillarius is a "special guy" in the Legion (not special in a bad way! :P ).

A realistic equivalent of a Lieutenant would be something that the Roman legion knew as an "Optio". They could use a true 2IC there.

**Comment by Operativ** [comment]
It's true that they don't utilise the full Roman legion ranks, unlike NCR who has a very wide span of the army ranks.

Either a Veteran Decanus (which indeed do appear in the universe, wearing a higher quality, veteran armour as mentioned by @companoo here), or perhaps a Praetorian (soldiers and officers with the potential to become a Centurion in the future) - although the Praetorians are more of a fistfighter in the fluff, and as we know fighting with fists in SS13 isn't the brightest idea without some kind of glove weapon.

If it falls on a Veteran Decanus, then it's going to be an easy addition, however a Praetorian might need a unique glove weapon that boosts unarmed damage.

If we don't count Vexillarius for aiding the Centurion (because they aren't really leading material, more of inspirational flag-bearing people), then my vote would be on a Veteran Decanus as it's rather simple to implement.

**Comment by roboticxlink** [comment]
This was veteran decanus yes? This can be closed?
