### ISSUE TITLE
Sherif and Deputy badges

### ISSUE THREAD

**Issue by inkticious** [BadDeathclaw/TG-Claw#280]
So uh, fox asked people to make some badge files, but I'm not sure how to do what they asked, sorry, I ain't the sharpest tool in the shed, but here's the original files, with the sprites of the badges.

[badges.zip](https://github.com/BadDeathclaw/TG-Claw/files/2677420/badges.zip)

**Comment by Garen7** [comment]
Working on this now, should be done soon.

**Comment by roboticxlink** [comment]
@Garen7 can you make them so that the sheriff badge can rename the other badges/etc? If you're working on functionality at least.

**Comment by Garen7** [comment]
@roboticxlink define what you mean when you say other badges, did you want the deputy to spawn with a box of deputy badges in his backpack? or have them in his office?

**Comment by roboticxlink** [comment]
@Garen7 Either box or in his office. Or both. But Deputy badges be limited and seperate from like, I'm gonna add nametags later on, too. But these will be specifically Den "law" enforcement.

**Comment by inkticious** [comment]
fun fact the oringal badge sprites i made used to say "DEN" in the center instead of just being the first letter of the role they where for.

**Comment by Garen7** [comment]
@inkticious hey the inhand sprites didn't line up with the hands so I didn't use them, if you can make sure it lines up with the hand then I can put it in whenever. Heres an image of what I mean when I say it doesn't line up.
![image](https://user-images.githubusercontent.com/22408776/50108556-23c45800-01fb-11e9-8e25-8c5d8b1b200d.png)
It should be in his left hand in this picture, in addition when its in the right hand and he's facing left you'll need to make sure that you clip out the space where the hand would be since its gunna just paste the image over the character. If you don't feel like going through and doing inhands I'm sure it'll be fine since there's lots of things in game with out inhands, however if you do make some, implementing it for me will be as simple as a drag and drop so I can just update it the instant you make them.
