### ISSUE TITLE
Have weight impact player movement speed

### ISSUE THREAD

**Issue by UndeadNappist** [BadDeathclaw/TG-Claw#499]
Add or use weight values already implemented and make it so the more you carry, the slower you move.

RP items that have no impact or armor - decorative clothing, piece of paper, pens, dice, etc. but are otherwise interesting would never have any weight.

**Comment by UndeadNappist** [comment]
It's also been recommend for having a gun out simply reduces your speed, but having it put on your back or in storage wouldn't.

**Comment by RenGusta** [comment]
The part of this that I see having the best utility is weapon-drawn mobility downsides. 

If a solid gap could be made between single and two handed weapons, I support this. 
For mobility downsides in general, I'd be interested in some independant testing to get a feel for how it'd perform live, before testing.

**Comment by Cadwell-Regis** [comment]
You mentioned before about wield delay which I very, very much want to see.

Jesus christ I honestly think if there was a momentary delay on wielding a gun from when you draw it from a bag/exosuit slot, it would just cut down drastically on RDM and encourage people to talk instead of blasting other players in the face every time they are threatened or insulted.

**Comment by UndeadNappist** [comment]
We're getting started with it. Part one. #612
