### ISSUE TITLE
NCR Profit Margin

### ISSUE THREAD

**Issue by UndeadNappist** [BadDeathclaw/TG-Claw#519]
Add a requirement or some sort of pressure for NCR to collect goods and monetary dosh and then delete it from the game.

This could be:
Collecting (taxes) and shipping them out on a train
Sharply limiting ammunition and doing a supply points/cash thing to get more ammunition and not providing NCR an easy way to get it (aka, removing their autolathe and gun benches)
Add a regular schedule to the reskinned supply shuttle so they can't control when it comes and goes, but they can actively go in the red if they ignore it (and admins can use it as an excuse to replace the commander or send the colonel to "investigate")
Removing their farms and other supplies and replacing it with this train system.
This _in theory_ should encourage them to maintain a regular flow of goods, but limiting their own base means they have to take control of territories - and coax them to produce goods without demolishing them in the process.

In turn, this means it'll be self-corrective over the long term: If they kill the people in control over those territories and there are limited jobslots for anything but raiders, you'll get a bunch of respawn raiders that start with guns and weaponry showing up and being problematic for you ; aka, actively punishing people who behave a certain way.

**Comment by Kimochiiiiiiiiiiiiii** [comment]
I like this, but doubt the NCR using peaceful ways of annexation. Good idea.

**Comment by Cadwell-Regis** [comment]
Considering the amount of work this involves, I feel like it would make more sense to have a neutral trade party as opposed to something only specific to the NCR Faction. As they will be the only ones who benefit from what would be a substantial amount of work. It's a bit more balanced and easier to control, if the Vendor can benefit any group of people or in better circumstances, all of them as opposed to one. 

https://docs.google.com/document/d/1zS5i_cvd-xad6nCWhvkuDqwfBs8t29GizFbfb9UPf84/edit

I did some work on a document when I thought about a system of conversion for money within F013, the main solutions to it was ensuring it was more hassle than alternative routes - meaning that farming is more efficient than relying on a Vendor.

Secondly you need to create a timer on how long it takes to retrieve goods, as the cost of obtaining supplies isn't just in monetary value but also in time devoted. Likely done by putting the Vendor on a different z-level only reachable by walking to the edge of the map.

I'd be willing to do all the pricing, figure out the cap amounts across the players so that for the most part, so this doesn't change power balance - only the dynamic of trade. No one will be richer, just certain individuals will obtain their supplies in different ways from before. 

An example of this being done is the Baystation Merchant Vendor, which I also tried to fix on Bay some time ago by re-doing all the prices. Never got the chance to get my changes put in, but it means I've done it before and that this is very doable.

**Comment by JTGSZ** [comment]
Faction cargo system. Monies can be turned in to generate credits, and the shuttle can just move across the map later on its in life.

**Comment by UndeadNappist** [comment]
I've been chatting to people and I'm actually coming around to the other way of thinking. Maybe the best way isn't necessarily to force them to get involved in difficult things or stealing. Maybe having a stable base they can stay in and RP in and isn't terrible with some things to do is the right way to go about things.

It's basically what legion has (with the opportunity for a few side missions) and seems to be working out more or less well.

**Comment by Cadwell-Regis** [comment]
You want them to have as few resources as possible, considering that factions are the only roles that have you spawn with a shitload of gear. The added co-operation and numbers they get also gives them a massive advantage over wastelanders and raiders, so it can sometimes seem like it's necessary to provide them with a whole lot of extra ammo, guns and supplies when the reality is - the kit  they start with is already an advantage itself.

Not advocating to neuter any factions, just pointing out it's fine to let them struggle a bit and deal with problems like running low on medicine, ammo or how it is they are going to expand. Taxation can work really well for them, though it'd make more sense for them to tax for supplies then caps, since that is what they'd spend their caps on anyway.

I definitely think why The Legion works is because, they can't just sit on their ass and survive round to round, they need to do active problem solving to feed themselves, stay supplied and to avoid being destroyed by the other factions. It's just a case of taking that fun and applying it to other places, like The Vault, BoS and NCR who would benefit from having to struggle a bit more.

Repeat - this does not mean take away their tools. Just make them work hard to stay fed and to obtain supplies like meds/ammo.
