### ISSUE TITLE
Make Combat Armor paintable.

### ISSUE THREAD

**Issue by GoodG1448** [BadDeathclaw/TG-Claw#639]
I like the idea that factions could claim combat armor by painting them. (Red for Legion - Khaki for NCR). Technically speaking there is already something like this in the code, the H.E.C.K suit that you get from killing bubblegum in regular /tg/ is paintable using a spray can. 

The thing is that I don't even know if it would work on combat armor by just slapping the code on it, AFAIK the H.E.C.K suit is White-ish grey and the Combat armor is green. It may or may not work, worth a try.

![paintable](https://user-images.githubusercontent.com/38330373/53247227-933e4400-3691-11e9-9fe7-207b4ef2c7c5.png)
![paintable2](https://user-images.githubusercontent.com/38330373/53247230-96393480-3691-11e9-9e24-dbbe9d7f4edd.png)

**Comment by UndeadNappist** [comment]
It's possible to recolor anything in the game by manually adjusting it. Sadly, because it operates by just flat adjusting the color of the entire sprite, it usually looks terrible as it mechanically maladjusts the color on an object.

This is usually circumvented by having a sprite composed of components that overlay each other, made white, and/or other processes.

Jumpsuits I believe operate like this (or at least I hope they are and aren't a million different identical sprited jumpsuits just with different colors but I think that's setting the bar too high for ss13). It was discussed at length at one point and it is doable, just complicated.

It is definitely, 100% possible.

**Comment by GoodG1448** [comment]
From my limited knowledge of /tg/code there a few things that can paint shit:

1) Crayon powder smoke/spray: I used to grind a crayon in a beaker then fill it with water, put that inside an E-cig with vaping set to medium and paint the tiles/people/items on the ground each time I puffed clouds of smoke near them. Smoke/Spray has potential.
2) Spray Can: AFAIK you can paint glass windows, people's faces, the H.E.C.K suit and curtains with it.
3) Paint buckets: Some were added when they added the raider mall in one of the stalls. You can only paint turf with it (Walls and tiles AFAIK).

Also there are multiple jumpsuit sprites, both for when they are formally and unformally worn. You can change jumpsuit colors by placing them inside a washer with any crayon and then turning it on. Same with gloves/shoes/caps.

**Comment by GoodG1448** [comment]
So I did a little experiment with the E-cig smoke trying to dye some of the armors. Turns out it worked out the way I expected.

![imagen](https://user-images.githubusercontent.com/38330373/53437068-70869500-39db-11e9-9681-cabf3576928d.png)
![imagen](https://user-images.githubusercontent.com/38330373/53437184-b3e10380-39db-11e9-8925-24a5e8d8eef9.png)

The steps to follow are:

1) Get a e-cig/smoke machine
2) Add crayon powder of any color mixed with water into the e-cig/smoke
3) Stand over the items you want to dye
4) Shower to remove the colors from your body
5) Go and equip the items you left on the ground
