### ISSUE TITLE
Scarcity

### ISSUE THREAD

**Issue by Kimochiiiiiiiiiiiiii** [BadDeathclaw/TG-Claw#653]
Make food be a a lot harder to find, this Will make people want to secure sources of food, make or raid them periodically.

**Comment by improvedname** [comment]
People rather walk starving

**Comment by Kimochiiiiiiiiiiiiii** [comment]
Then it's shit rp, not my problem that they decide to break their immersion.Removing fridges from the wasteland would also be a good idea, or their contents (6+ milk catrons and 2 egg boxes)

**Comment by UndeadNappist** [comment]
Consolidating prizes into one place and having them in specific, related areas (aka kitchens) gives an overall theme to these places coupled with all the feral ghouls. The implication is you're moving into a town that slowly had it's inhabitants go mad.

More places need to have the details shaped to lend the implication of a story or a theme without otherwise stating it; I wouldn't be against you changing them to radioactive eggs and milk, or rotten eggs and milk.

The constant hunger and thirst bar that dropped constantly is a nuisance since it's balanced for hour-long rounds top, so that'll have to be tweaked too.

**Comment by Kimochiiiiiiiiiiiiii** [comment]
This issue is meant so that people need to focus more on resources, food in this case. If you make food harder to find it'd be pointless to then lower the hunger rate. Since the fridges are to be in that area then how about the contents are severally reduced (for example; three/one vegetable/fruit objects and two milk cartons in each fridge)

**Comment by UndeadNappist** [comment]
It's not pointless. It's tedious and annoying to constantly have to scarf up food every ten minutes.

But if there's the same level of work and danger and scarcity but you only have to do it ONCE (or maybe twice if the round goes on very long), it cuts out a lot of the running around for players while maintaining the same level of work, scarcity, and danger.

**Comment by JohnOxford** [comment]
considering making a PR that just removes food and ammunition on the map in general. if you want food you can eat the mobs or each other (or grow it like everyone else in human history)

**Comment by UndeadNappist** [comment]
I remember having a whole long discussion on this and should've saved it as an issue. Basically, two reasons;
One: to establish **theme** of a particular area. Kitchens and farms have food. Maybe the food should be replaced by loot tables, or only have radioactive food like dandy apples, but there you are.
Two: To give players something to do (I need to eat, and also need ammo to protect myself, so I want to scav) that isn't just 'grief everyone else'.
Overall there's a reason many of the autolathes across the map have been replaced with constructionlathes, and why they have been left where they are.

Until the gunpowder PR from oculus with crafting tables would go through, I caution against removing ammunition across the map.

**Comment by JohnOxford** [comment]
i could make simple crafting recipes(possibly port from drymouth/oldcode) that lets you handcraft shells with charcoal in a beaker and spent shell casings, then only make it for really common ones like 5.56 and 9mm

theres also a cartridge loader item in other revisions that's apart of the crafting for making shells, could add that to loot tables.

food however wouldn't at all be a problem, with the sheer amount of mobs we have, you can butcher all of them for atleast one meat a piece, and i -think- you can breed brahmin/cows/chickens ect, milk also gives sustenance and theres farming and shit

the question being is if adding scarcity is going to make players quit when they expend all their ammo/are starving to death or end up griefing other people for their items

in a perfect universe we'd see a system from the first two metro games where bullets that are unique or rare are valuable

**Comment by UndeadNappist** [comment]
Would need more chickens and brahmin on the map and also tweak them so they don't just insta-die before anyone finds them due to how nearby hostile mobs are sitting around them.

Wastemob bots no longer attack farm animals, so you could actually protect them by putting gutsies and handies nearby or in the pen with them.

**Comment by JohnOxford** [comment]
im remaking this issue so i can add a checklist of things that involve scarcity and how we're going to work torwards this, i'll reference this as a beginning conversation
