### ISSUE TITLE
harsher medical

### ISSUE THREAD

**Issue by companoo** [BadDeathclaw/TG-Claw#668]
can we get a harsher medical system so that surgery might be required for stuff

stimpaks arent god squad fix everything

among other things

**Comment by UndeadNappist** [comment]
Why this is a bad idea:
1. Chems will do everything anyway, because of how ridiculous chems are right now.
2. It's tedious, you spend a lot of time doing shit where you can't do anything else
3. The tedium isn't enjoyable
4. entry-level to doctoring and getting engaged in the medical process has a steep curve that if you fuck up, whoops, your patient just died and you screwed a player
5. it happens all the fucking time because ss13 is a high lethality game
6. it's extremely repetitive
7. you feel like you're constantly under pressure because of that especially as multiple people roll in
etc
8. Stimpaks ARE god squad fix everything in the fallout universe.

I've had hour-long discussions about bay med and it's upsides and downsides, and this has a similar basis into why that was created. This is a horrible idea as medical currently stands.

You're better off looking at what's currently wrong with chemistry https://github.com/BadDeathclaw/TG-Claw/issues/537

You can also saw limbs off, forcing people to reattach them. Surgery is there to fill that gap.

Problem is people **die before it becomes relevant**.
