### ISSUE TITLE
Adds Guns/Ammo/Food Wasteland Machines ; rework vending machines to consume money

### ISSUE THREAD

**Issue by Raze500** [BadDeathclaw/TG-Claw#676]
Machines to eat your caps and stuff beacuse kinda trading with fools is outdated.

¡And of course will hella expensive beacuse capitalism!

Ah yeah i will port it on monday.

The idea of course is to add machines so players can buy shit in different places, maybe one to get tools too! 

Those machines will not be hacked but i guess it can be destructible 

Make me a trialcoder when *starts bitching in spanish*

**Comment by Kimochiiiiiiiiiiiiii** [comment]
No, fuck off, this was already in Outcasts and it's a bad thing to put in the game, the experience was shit.

**Comment by Kimochiiiiiiiiiiiiii** [comment]
The idea is not to buy from a machine but to buy from another player.

**Comment by JTGSZ** [comment]
I agree with him there actually. The machines would just be the easy solution, and at the same time make the world feel more sterile.

**Comment by JohnOxford** [comment]
i'm for adding a gunrunners robot, putting it away from any faction bases, making the guns r e t a r d e d expensive, and just listing most of the commonly found guns with one or two that are unique (maybe just a GRA version of a standard gun) for a extraordinary amount of caps

but other than that, machines to get ammo/guns/medical stuff isn't appropriate to this game and since guns aren't really that different between each other, it would really just turn this into a shittier version of borderlands

and as kimo stated above, this was tried on outcasts and was a really shitty way to encourage roleplay.

**Comment by imw-Oculus** [comment]
No thank you. Vending machines which accept caps make no IC sense. A Gun-Runners robot would be acceptable, ideally with the caps required to actually get a gun requiring serious resources to attain - and nothing for sale that's considered a top-tier weapon. 

Now, on the other hand - vending machines that can be constructed by players, stocked with items by players, with items with prices in caps set by players...

**Comment by JohnOxford** [comment]
we rust now
