### ISSUE TITLE
Pahrump map issues

### ISSUE THREAD

**Issue by GhostEcho** [BadDeathclaw/TG-Claw#974]
Report bugs and issues, as well as suggestions here

**Comment by BigManClancy** [comment]
You are unable to place locks on doors, this was the case for both the preset wooden doors and premade wooden doors, not tested on other forms of doors y

This map is way too small, NCR and Legion war is a matter of just running straight down the street to eachother, overall the map is way too small.

I appreciate wanting to make the Legion more vulnerable by giving them a 2nd entrance, but it just ends with the NCR just stomping the Legion if they push the base.

There is not a single Sink in Kabob.

This map is a needless addition to the server, the old map had it's issues but was almost unanimously liked by everybody, it is clear from reading OOC and generally just anyone i see that nobody wants this map, and it will definitely need some work.
I  can definitely see the appeal of making a smaller, more densely packed map but it just does not gel well with the term "Mojave WASTEland". You keep running into people within moments of eachother rather than there being minutes of downtime before seeing another person.

Will continue to update in this thread about more bugs and suggestions as i play this horrendous map.

**Comment by GhostEcho** [comment]
Tfw you say no one likes it and yet in the same round several people said they like it like Polys

**Comment by GhostEcho** [comment]
Also as for legion vs ncr, I would argue its allows for my areas of assault amd ways to escape, considering there were about two main roads on the old map that you had conflicts on, and escaping/engaging from desert was a death sentence

**Comment by BigManClancy** [comment]
"Tfw you say no one likes it and yet in the same round several people said they like it like Polys".
Yeah, but at the same time people all voted to restart on literally the first restart vote that came up.

This is literally a "NCR vs Legion" map, everything on the side such as The Den, BOS, Vault feels like it is entirely useless and contributes little to nothing to the round, when on the other map they were enough of a presence to have an impact, you could constantly see something happen at the Den. This doesn't happen on Pahrump.

**Comment by GhostEcho** [comment]
The old map was just as much of a NCR vs Legion map, hell 90% of rounds get restarted on the basis that NCR or Legion dies, so I quite frankly have little comprehension of your opinions when they're for the most part either infactual or issues that apply just as much, if not MORE to the other map, considering you bring up the vault as something that has an impact on the round

**Comment by SeniorScore** [comment]
As Ghost said, the other map has A SINGULAR CROSSING POINT FOR NIGH ALL TRAFFIC ON THE ROADS
It's easier for Legion and NCR (and other groups for that matter) to slip around each other on this map. And I don't think this is a bad thing. As for their influence on the round, i think lack of map knowledge is also a contributing factor.

**Comment by BigManClancy** [comment]
Then atleast give people an option to opt-in or out of testing this map, it is clear that a lot of people are not happy with the mere fact of it existing, so either make it a map vote at the beginning/end of rounds or make a smaller-size testing server for this. I am too much of an idiot to properly bring over my points for not liking the map it seems so that is really just the best suggestion i can give.

**Comment by GhostEcho** [comment]
thats pretty much the plan for the map voting

**Comment by SeniorScore** [comment]
unrelated: expanding the farming portion, as well as giving Legion towercaps (and _maybe_ xander and broc) on start would help a bit. Also the southern tunnel gate was just not responding to button presses.

**Comment by BigManClancy** [comment]
[Tested with MiranEitan]

I have attempted 4 times total to refill a Defibrilator in the NCR base with power cells created in the NCR autolathe, all of the inserted cells would not charge the Defib, and when removed would immediatly be at 0%. This is 100% consistent and easy to recreate.

Upon bringing this to Admin MiranEitan they spawned me a power cell, which miraculously worked, prompting me to try and check the consistency of the lathe power cells not working.

**Comment by GhostEcho** [comment]
Did you um, charge the autolathe cells???

**Comment by GhostEcho** [comment]
They dont start charged

**Comment by BigManClancy** [comment]
They do, when they are brought out they are at a 100% charge.

**Comment by BigManClancy** [comment]
Also to add on: it is neigh impossible to keep power going in the NCR base, i would really love a way of setting up solars so that atleast during the day you can charge some power. As it stands playing MO makes me want to neck myself cause i get like 2-3 minutes of power and then an outage for the next 30-40 minutes.

**Comment by companoo** [comment]
solars is a good idea

**Comment by Cactus2388** [comment]
Padlocks can't be placed on fence doors making it impossible to brig people, they work perfectly on regular doors.

**Comment by Cactus2388** [comment]
the autolathe reloading bench can only remove glass put inside it by printing individual solid beakers. It'd be nice if it could print glass and metal sheets so that you can remove the mats.

**Comment by Cactus2388** [comment]
NCR base has no trashcans

**Comment by BigManClancy** [comment]
The Power Cell issue from Lathe Power Cells being full but actually being empty is still not fixed.

**Comment by BigManClancy** [comment]
Also: I am not a fan closing instantly after you walk through them, i preferred if they stay opened like on the old map. It kinda sucks.

**Comment by BigManClancy** [comment]
Alright, i have just finished this round and actually went through the hassle of trying out solars. And they work beautifully once set up (This is my first time setting solars up ever in my life pls no hate)#

On a more suggestive note: The amount of Uranium that is supplied with the generator is way too much. I say lowering the Uranium supply down to 15-25 Uranium is better, it keeps the gen going for a while while also not being able to sustain it for the entire round. The solars worked perfectly once set up, they supplied the APC with enough power to be able to rely on it, but NOT enough power to entirely make it a non-issue, breaking the solars is also incredibly easy for the Legion to do, so having to defend them could make for a great dynamic where the Legion tries to sabotage the shit out of the NCR to prevent them from having power (Which they rely on for the lathe, chem makers etc.

Okay. Upon testing said theory on sabotaging the solar panels i can safely say, taking out 6 out of the 12 solar panels is enough to make the power outage not be able to charge the APC on it's own anymore, meaning that 12 solar panels is a great balance. Though i have not tested this setup with a chem maker and chem dispenser taking up power yet.
![6fN3QGl](https://user-images.githubusercontent.com/51722986/59418083-adc73500-8dc8-11e9-913a-8cd7365acf05.jpg)

**Comment by Hekzder** [comment]
Going to close this for now in favor of letting each individual map issue have it's own Git issue created for it, as people report them and make issues.
